export * from '@/pages/app/persons/components/delete-person'
export * from '@/pages/app/persons/components/edit-person'
export * from '@/pages/app/persons/components/person-details'
export * from '@/pages/app/persons/components/person-details-skeleton'
export * from '@/pages/app/persons/components/person-edit-skeleton'
export * from '@/pages/app/persons/components/person-table-filters'
export * from '@/pages/app/persons/components/register-new-person'
